name: Auto 8 Min Bot
on:
  schedule:
    - cron: '0 3 * * *'
    - cron: '0 11 * * *'
    - cron: '0 19 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install moviepy==1.0.3 requests && sudo apt-get install -y ffmpeg
      - run: python bot.py
        env:
          PIXABAY_KEY: ${{ secrets.PIXABAY_KEY }}
